### ISSUE TITLE
Adding Licensing

### ISSUE THREAD

**Issue by carl-krikorian** [lulia0228/Document_IE#2]
Hello,
I am a big fan of the algorithm and implementation of GCNs made in this repo. It could be a valuable resource for the community and I wanted to see if I could make my own fork with your permission and expand on the work done here. 
Given that the main reference and paper (https://github.com/tkipf/gcn) is licensed under the permissive MIT License. I wanted to reach out and kindly request if you would consider adding an open-source license, such as the MIT License.
Thank you for your time, best regards.

**Comment by lulia0228** [comment]
> Hello, I am a big fan of the algorithm and implementation of GCNs made in this repo. It could be a valuable resource for the community and I wanted to see if I could make my own fork with your permission and expand on the work done here. Given that the main reference and paper (https://github.com/tkipf/gcn) is licensed under the permissive MIT License. I wanted to reach out and kindly request if you would consider adding an open-source license, such as the MIT License. Thank you for your time, best regards.

Thank you for your attention. I have added License.

**Comment by carl-krikorian** [comment]
Thank you for the swift action and this wonderful repo!
